language: node_js
node_js:
  - 'stable'
cache:
  - pip
  directories:
    - node_modules
python:
  - "3.5"
install:
  - pip install --user awscli
script:
  - npm test
  - npm run test:coverage
  - npm run build
deploy:
  provider: s3
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $SECRET_ACCESS_KEY
  bucket: cdotfo
  region: eu-west-1
  skip_cleanup: true
  acl: public_read
  keep_history: true
  local_dir: build
  on:
    branch: master
after_deploy:
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"