const Language = {
  en: {
    overview: 'Overview',
    invoice: 'Invoice',
    bills: 'Bills',
    transactions: 'Transactions',
    customers: 'Customers',
    products: 'Products',
    name: 'Name',
    accounts: 'Accounts',
    companies: 'Companies',
    sales: 'Sales',
    login: 'Login',
    logout: 'Logout',
    addcompany: 'Add Company',
    addaccount: 'Add account',
    addproduct: 'Add product',
    cancel: 'Cancel',
    add: 'Add',
    daybook: 'Day Book',
    choosecompany: 'Choose company',
    fillformtoaddaccount: 'Fill this form to add an account',
    fillformtoaddbill: 'Fill this form to add a bill',
    vendor: 'Vendor',
    expense: 'Expense',
    attachment: 'Attachment',
    description : 'Description',
    payment: 'Payment',
    tax: 'Tax',
    billreceived: "Bill Received",
    paymentdue: "Payment Due",
    fillformtoaddproduct: 'Fill this form to add a product',
  },
  fo: {
    overview: 'Yvirlit',
    invoice: 'Faktura',
    bills: 'Rokningar',
    transactions: 'Flytingar',
    customers: 'Kundar',
    products: 'Vørur',
    addaccount: 'Legg kontu avtrat',
    addbill: 'Legg rokning avtrat',
    addproduct: 'Legg vøru avtrat',
    accounts: 'Kontur',
    name: 'Navn',
    companies: 'Fyritøkur',
    sales: 'Sølur',
    login: 'Rita inn',
    logout: 'Rita út',
    addcompany: 'Stovna fyritøku',
    cancel: 'Strika',
    add: 'Legg afturat',
    daybook: 'Kassa Kladda',
    choosecompany: 'Vel fyritøku',
    fillformtoaddaccount: 'Fyll teiðarnar fyri at leggja kontu avtrat',
    fillformtoaddbill: 'Fyll teiðarnar fyri at leggja rokning avtrat',
    vendor: 'Seljari',
    expense: 'Kostnaðarslag',
    attachment: 'Fylgiskjal',
    description: 'Frágreiðing',
    payment: 'Rindan',
    tax: 'Skattur',
    billreceived: 'Rokningin móttikin',
    paymentdue: 'Rokningin til gjladingar',
    fillformtoaddproduct: 'Fyll teiðarnar fyri at leggja eina vøru avtrat',
  },
  de: {
    overview: 'Übersicht',
    invoice: 'Rechnung',
    bills: 'Rechnungen',
    transactions: 'Transaktionen',
    customers: 'Kunden',
    products: 'Produkte',
    companies: 'Firmen',
    addaccount: 'Konto hinzufügen',
    addbill: 'Rechnung hinzufügen',
    addproduct: 'Produkte hinzufügen',
    name: 'Name',
    accounts: 'Konten',
    sales: 'Verkauf',
    login: 'Anmeldung',
    logout: 'Ausloggen',
    addcompany: 'Firma Hinzufügen',
    cancel: 'Stornieren',
    add: 'Hinzufügen',
    daybook: 'Tagebuch',
    choosecompany: 'Firma wählen',
    fillformtoaddaccount:
      'Füllen Sie dieses Formular aus, um ein Konto hinzuzufügen',
    fillformtoaddbill: 'Füllen Sie dieses Formular aus, um ein Rechnung hinzuzufügen',
    vendor: 'Verkäufer',
    expense: 'Kostenaufwand',
    attachment: 'Befestigung',
    description: 'Beschreibung',
    payment: 'Zahlung',
    tax: 'Besteuern',
    billreceived: 'Rechnung Erhalten',
    paymentdue: 'Zahlung Fällig',
    fillformtoaddproduct:
      'Füllen Sie dieses Formular aus, um eine Produkte hinzuzufügen',
  },
}

export default Language
