const Language = {
  en: {
    account: 'Account',
    accountnumber: 'Account number',
    accounts: 'Accounts',
    add: 'Add',
    addcompany: 'Add Company',
    addaccount: 'Add account',
    addaccountnumber: 'Add account number',
    addcustomer: 'Add customer',
    addproduct: 'Add product',
    assets: 'Assets',
    addtransaction: 'Add transaction',
    bankname: 'Bank name',
    balance: 'Balance',
    bill: 'Bill',
    attachment: 'Attachment',
    bills: 'Bills',
    billreceived: 'Bill Received',
    cancel: 'Cancel',
    choosecompany: 'Choose company',
    companies: 'Companies',
    credit: 'credit',
    customer: 'Customer',
    customers: 'Customers',
    customersuccessfullyupdated: 'Customer successfully updated',
    datepaid: 'Date paid',
    daybook: 'Day Book',
    debts: 'Debts',
    debit: 'debit',
    delete: 'Delete',
    description: 'Description',
    downloadinvoice: 'Download invoice as pdf file',
    errorloadingaccounts: 'Error loading accounts',
    errorloadingbills: 'Error loading bills',
    errorloadingexpenses: 'Error loading expenses',
    errorloadingtransactions: 'Error loading transactions',
    errorloadingvendor: 'Error loading vendor',
    expense: 'Expense',
    expensename: 'Expense name',
    expenses: 'Expenses',
    fillformtoaddaccount: 'Fill this form to add an account',
    fillformtoaddbill: 'Fill this form to add a bill',
    fillformtoaddproduct: 'Fill this form to add a product',
    fillformtoaddcustomer: 'Fill this form to update customer',
    fillformtoaddvendor: 'Fill this form to add a vendor',
    fillformtoaddtransaction: 'Fill this form to add a transaction',
    fillformtoupdateexpense: 'Fill this form to update expense',
    fillformtoupdatevendor: 'Fill or change this form to update vendor',
    id: 'Id',
    income: 'Income',
    invoice: 'Invoice',
    invoicecreated: 'Invoice created',
    invoicedue: 'Invoice due date',
    invoicenumber: 'Invoice number',
    loading: 'Loading',
    login: 'Login',
    logout: 'Logout',
    name: 'Name',
    nameisrequired: 'Name is required',
    no: 'No',
    overview: 'Overview',
    paid: 'Paid',
    paybill: 'Pay bill',
    payment: 'Payment',
    paymentdue: 'Payment Due',
    price: 'Price',
    product: 'Product',
    products: 'Products',
    received: 'Received',
    removefromlist: 'Remove item from list',
    sales: 'Sales',
    sum: 'Sum',
    tax: 'Tax',
    transactions: 'Transactions',
    type: 'Type',
    total: 'Total',
    yes: 'Yes',
    update: 'Update',
    updatecustomer: 'Update customer',
    updateproduct: 'Update product',
    updatevendor: 'Update vendor',
    updateexpense: 'Update expense',
    vendor: 'Vendor',
    vendorname: 'Vendor name',
    quantity: 'Quantity',
  },
  fo: {
    addaccount: 'Legg kontu avtrat',
    addaccountnumber: 'Legg kontu nummar avtrat',
    addbill: 'Legg rokning avtrat',
    addproduct: 'Legg vøru avtrat',
    account: 'Konta',
    accountnumber: 'Kontu nummar',
    accounts: 'Kontur',
    add: 'Legg afturat',
    addcompany: 'Stovna fyritøku',
    addcustomer: 'Legg kunda avtrat',
    assets: 'Ognir',
    addtransaction: 'Legg transaktion avtrat',
    attachment: 'Fylgiskjal',
    bankname: 'Navn á banka',
    balance: 'Upphædd',
    bill: 'Rokning',
    bills: 'Rokningar',
    billreceived: 'Rokningin móttikin',
    cancel: 'Strika',
    choosecompany: 'Vel fyritøku',
    companies: 'Fyritøkur',
    credit: 'Kredit',
    customer: 'Kundi',
    customers: 'Kundar',
    customersuccessfullyupdated: '',
    datepaid: 'Goldið tann',
    daybook: 'Kassa Kladda',
    debts: 'Skuldir',
    delete: 'Strika',
    description: 'Frágreiðing',
    downloadinvoice: 'Tak fakturaðin niður sum pdf fílu',
    errorloadingaccounts: 'Villa íkomin undir innlesing av kontum',
    errorloadingbills: 'Riggaði ikki at heinta rokningar',
    errorloadingexpenses: 'Villa íkomin undir innlesing av kostnaðum',
    errorloadingtransactions: 'Villa íkomin undir innlesing',
    errorloadingvendor: 'Villa íkomin undir innlesing av seljarum',
    expense: 'Kostnaðarslag',
    expensename: 'Kostnaðarslag',
    expenses: 'Utreiðslur',
    debit: 'Debit',
    fillformtoaddaccount: 'Fyll teigarnar fyri at leggja kontu avtrat',
    fillformtoaddbill: 'Fyll teigarnar fyri at leggja rokning avtrat',
    fillformtoaddtransaction:
      'Fyll teigarnar fyri at leggja transaktion avtrat',
    fillformtoaddvendor: 'Fyll teigarnar fyri at leggja seljara avtrat',
    fillformtoupdateexpense: 'Fyll teigarnar fyri at dagføra seljara',
    fillformtoupdatecustomer: 'Fyll teigarar fyri at dagføra kundan',
    fillformtoupdatevendor: 'Fyll teigarar fyri at dagføra útreiðsluslag',
    fillformtoaddproduct: 'Fyll teiðarnar fyri at leggja eina vøru avtrat',
    id: 'Eyðmerkingarnummar',
    income: 'Inntøkur',
    invoice: 'Faktura',
    invoicecreated: 'Fakturi stovnaður',
    invoicedue: 'Fakturi til galdingar',
    invoicenumber: 'Faktura nummar',
    loading: 'Innlesur',
    login: 'Rita inn',
    logout: 'Rita út',
    name: 'Navn',
    nameisrequired: 'Navn er kravt',
    no: 'Nei',
    overview: 'Yvirlit',
    paid: 'Goldið',
    paybill: 'Gjald rokning',
    payment: 'Rindan',
    paymentdue: 'Rokningin til gjladingar',
    price: 'Kostnaður',
    product: 'Vøra',
    products: 'Vørur',
    received: 'Móttikin',
    removefromlist: 'Strika vøru av lista',
    sales: 'Sølur',
    sum: 'Peningaupphædd ',
    tax: 'Skattur',
    type: 'Slag',
    transactions: 'Flytingar',
    total: 'Samantalt',
    update: 'Dagfør',
    updateproduct: 'Dagfør vøru',
    updatecustomer: 'Dagfør kunda',
    updatevendor: 'Dagfør seljara',
    updateexpense: 'Dagfør útreiðsluslag',
    yes: 'Ja',
    vendor: 'Seljari',
    vendorname: 'Navn á seljara',
    vendors: 'Seljarir',
    vendorsuccessfullyupdated: 'Tað eydnaðist at dagføra seljara',
    quantity: 'Nøgd',
  },
  de: {
    addaccount: 'Konto hinzufügen',
    addaccountnumber: 'Konto nummer hinzufügen',
    addbill: 'Rechnung hinzufügen',
    addproduct: 'Produkte hinzufügen',
    addtransaction: 'Transaktione hinzufügen',
    account: 'Konte',
    accountnumber: 'Konte nummer',
    accounts: 'Konten',
    add: 'Hinzufügen',
    addcompany: 'Firma Hinzufügen',
    addcustomer: 'Kunden hinzufügen',
    assets: 'Vermögenswerte',
    attachment: 'Befestigung',
    bankname: 'Bank Name',
    balance: 'Balance',
    bill: 'Rechnung',
    billreceived: 'Rechnung Erhalten',
    bills: 'Rechnungen',
    cancel: 'Stornieren',
    choosecompany: 'Firma wählen',
    companies: 'Firmen',
    credit: 'Credit',
    customer: 'Kunde',
    customers: 'Kunden',
    customersuccessfullyupdated: '',
    datepaid: 'Zahlungsdatum',
    daybook: 'Tagebuch',
    debts: 'Schulden',
    delete: 'Löschen',
    debit: 'Debit',
    description: 'Beschreibung',
    downloadinvoice: 'Rechnung als pdf herunterladen',
    errorloadingaccounts: 'Fehler beim Laden der Konten',
    errorloadingbills: 'Fehler beim Laden der Rechnungen',
    errorloadingexpenses: 'Fehler beim Laden der Ausgaben',
    errorloadingcustomer: 'Fehler beim Laden der Kunden',
    errorloadingtransactions: 'Fehler beim Laden der Transaktionen',
    errorloadingvendor: 'Fehler beim Laden des Anbieters',
    expense: 'Kostenaufwand',
    expensename: 'Kostenaufwand name',
    expenses: 'Kostenaufwande',
    fillformtoaddaccount:
      'Füllen Sie dieses Formular aus, um ein Konto hinzuzufügen',
    fillformtoaddbill:
      'Füllen Sie dieses Formular aus, um ein Rechnung hinzuzufügen',
    fillformtoaddproduct:
      'Füllen Sie dieses Formular aus, um eine Produkte hinzuzufügen',
    fillformtoaddvendor:
      'Füllen Sie dieses Formular aus, um ein Verkäufer hinzuzufügen',
    fillformtoupdateexpense:
      'Füllen Sie dieses Formular aus, um ein Kostenaufwand aktualisieren',
    fillformtoupdatecustomer:
      'Füllen Sie dieses Formular aus, um ein Kunden aktualisieren',
    fillformtoupdatevendor:
      'Füllen Sie dieses Formular aus, um ein Verkäufer aktualisieren',
    fillformtoaddtransaction:
      'Füllen Sie dieses Formular aus, um ein Transaktionen hinzuzufügen',
    id: 'Id',
    income: 'Einkommen',
    invoice: 'Rechnung',
    invoicecreated: 'Rechnung erstellt',
    invoicedue: 'Rechnungsfälligkeitsdatum',
    invoicenumber: 'Rechnungsnummer',
    loading: 'Wird geladen',
    login: 'Anmeldung',
    logout: 'Ausloggen',
    name: 'Name',
    nameisrequired: 'Name ist erforderlich',
    no: 'Nein',
    overview: 'Übersicht',
    paid: 'Bezahlt',
    paybill: 'Rechnung bezahlen',
    payment: 'Zahlung',
    paymentdue: 'Zahlung Fällig',
    price: 'Preis',
    product: 'Produkt',
    products: 'Produkte',
    received: 'Empfangen',
    removefromlist: 'Element aus Liste entfernen',
    sales: 'Verkauf',
    sum: 'Summe',
    tax: 'Besteuern',
    type: 'Art',
    transactions: 'Transaktionen',
    total: 'Gesamt',
    update: 'Aktualisieren',
    updateproduct: 'Produkt aktualisieren',
    updatecustomer: 'Kunden aktualisieren',
    updateexpense: 'Verkaufer aktualisieren',
    vendor: 'Verkäufer',
    vendorname: 'Verkäufer name',
    vendors: 'Verkäufer',
    vendorsuccessfullyupdated: 'Verkäufer wurde erfolgreich hinzugefügt',
    yes: 'Ja',
    quantity: 'Menge',
  },
}

export default Language
