const Language = {
  fo: {
    overview: 'Yvirlit',
    invoice: 'Faktura',
    bills: 'Rokningar',
    transactions: 'Flytingar',
    customers: 'Kundar',
    products: 'Vørur',
    accounts: 'Kontur',
    sales: 'Sølur',
    login: 'Rita inn',
    logout: 'Rita út',
  },
  en: {
    overview: 'Overview',
    invoice: 'Invoice',
    bills: 'Bills',
    transactions: 'Transactions',
    customers: 'Customers',
    products: 'Products',
    accounts: 'Accounts',
    sales: 'Sales',
    login: 'Login',
    logout: 'Logout',
  },
  de: {
    overview: 'Übersicht',
    invoice: 'Rechnung',
    bills: 'Rechnungen',
    transactions: 'Transaktionen',
    customers: 'Kunden',
    products: 'Produkte',
    accounts: 'Konten',
    sales: 'Verkauf',
    login: 'Anmeldung',
    logout: 'Ausloggen',
  },
}

export default Language
